name: Add label on pull request

on:
    pull_request:
        types: opened

permissions:
    id-token: write
    contents: write
    pull-requests: write

jobs:
    add-label:
        runs-on: ubuntu-latest
        steps:
            - name: Get PR number
              id: pr_number
              run: echo "${{ github.ref }}"
            - name: Add label
              env:
                GH_TOKEN: ${{ github.token }}
              run: |
                gh pr edit ${{ github.ref }} --add-label "needs-review"
                echo "${{ github.event }}"
                
            