name: Add label on pull request

on:
    pull_request:
        types: [opened, reopened]

permissions:
    id-token: write
    contents: write
    pull-requests: write

jobs:
    add-label:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Get PR number
              id: pr_number
              run: echo "${{ github.ref }}"
            - name: Add label
              env:
                GH_TOKEN: ${{ github.token }}
              run: |
                number=$(echo "${{ github.ref }}" | awk -F'/' '{print $3}')
                gh pr edit "$number" --add-label "needs-review"
                echo "${{ github.event }}"
                
            