name: Cache workflow

on: push

permissions:
    contents: read
    id-token: write

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            
            - name: datetime
              id: datetime
              run: |
                now=$(date +%s)
                echo "now=$now" | tee -a $GITHUB_OUTPUT

            - name: mkdir
              run: |
                mkdir -p ${{ github.workspace }}/src_${{ steps.datetime.outputs.now }}
                cp -r ${{ github.workspace }}/src ${{ github.workspace }}/src_${{ steps.datetime.outputs.now }}

            - name: cache
              uses: actions/cache@v4
              with:
                path: ${{ github.workspace }}/src_${{ steps.datetime.outputs.now }}
                key: test
            
            - name: outputs
              run: |
                echo "cache-hit=${{ steps.cache.outputs.cache-hit }}"