name: Cache workflow

on: workflow_dispatch

permissions:
    contents: read
    id-token: write

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: cache
              uses: actions/cache@v2
              with:
                path: ${{ github.workspace }}/src
                key: test
            
            - name: outputs
              run: |
                echo "cache-hit=${{ steps.cache.outputs.cache-hit }}"