name: Call reusable workflow
on: push
jobs:
    call:
        uses: lonely-takumi/reusable-workflow-repository/.github/workflows/reusable-workflow.yml@main
        permissions:
            contents: read
        with:
            input_1: "ttttttttttttttttttttttest"
        secrets:
            token: ${{ secrets.CLOUD_ID }}