name: Call reusable workflow
on: push
jobs:
    set-env:
        runs-on: ubuntu-latest
        environment: DEV
        outputs:
            secret-id: ${{ steps.secret-id.outputs.secret-id}}
        steps:
            - name: set secret
              id: secret-id
              run: |
                secretId=${{ secrets.MASTER_ID}}
                echo "secret-id=$secretId" >> $GITHUB_OUTPUT
    # call:
    #     needs: set-env
    #     uses: lonely-takumi/reusable-workflow-repository/.github/workflows/reusable-workflow.yml@main
    #     permissions:
    #         contents: read
    #     with:
    #         input_1: ${{ needs.set-env.outputs.secret-id}}
    #     secrets:
    #         cloud_id: ${{ secrets.CLOUD_ID }}
    call:
        needs: set-env
        uses: lonely-takumi/reusable-workflow-repository/.github/workflows/reusable-workflow.yml@v1
        permissions:
            contents: read
        with:
            input_1: ${{ needs.set-env.outputs.secret-id}}
            id: main
        secrets: inherit