name: Call reusable workflow
on: workflow_dispatch
permissions:
    contents: read
    id-token: write
    actions: read
jobs:
    set-env:
        runs-on: ubuntu-latest
        environment: DEV
        outputs:
            secret-id: ${{ steps.secret-id.outputs.secret-id}}
        steps:
            - name: set secret
              id: secret-id
              run: |
                secretId=${{ secrets.MASTER_ID}}
                echo "secret-id=$secretId" >> $GITHUB_OUTPUT
    
    call:
        needs: set-env
        uses: lonely-takumi/reusable-workflow-repository/.github/workflows/reusable-workflow.yml@main