name: Contexts
on : push
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            - run : | 
                echo "${{github.actor}}"
                echo "${GITHUB_ACTOR}"
                echo "${{runner.os}}"
                echo "${{runner.name}}"
