name: echo

on: push

jobs:
    echo:
        environment: DEV
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4

            - name: echo
              run: |
                cd ..
                cd ..
                cd _actions/actions/checkout/11bd71901bbe5b1630ceea73d27597364c9af683
                git tag --contains 11bd71901bbe5b1630ceea73d27597364c9af683
                ls
                # cat parameters.json

            - name: edit
              run: |
                jq '.parameters.loginPassword.value = "${{ secrets.MASTER_ID }}"' parameters.json > new_parameters.json
                cat new_parameters.json

            - name: convert json to jsonc
              run: |
                cat new_parameters.json > parameters.jsonc
                ls
                cat parameters.jsonc

            - name: add comment
              run: |
                comment="/*
                This is a comment.
                fjp;eof:waopjfo
                fmopwe:apowejf:
                  fkaopwje:oafkwe[]ap
                  kfoea:jofeakpeka
                epwak:qa@wpekpfwe
                */"
                # add comment to last line of parameters.jsonc
                echo "$comment" >> parameters.jsonc
                cat parameters.jsonc
