name: echo

on: push

jobs:
    echo:
        environment: DEV
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: echo
              run: |
                 cat parameters.jsonc

            - name: edit
              run: |
                jq '.parameters.loginPassword = "${{ secrets.DEV }}"' parameters.json > parameters.json
                cat parameters.json