name: use another repository action
on: push
jobs:
    test-action:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with: 
                path: main
            - name: check directory
              run: |
                ls
            - name: checkout another repository
              uses: actions/checkout@v4
              with:
                repository: lonely-takumi/reusable-workflow-repository
                ref: main
                path: sub
            - name: check directory
              run: |
                ls
            - name: move work directory
              run: |
                cd ${{ github.workspace }}/main
                ls
                cd ${{ github.workspace }}/sub
                ls
                cd ${{ github.workspace }}/sub/.github/actions/test-action
                ls
            - name: use another repository action
              uses: ./sub/.github/actions/test-action
              with:
                input_1: "fwjfiowjf"
