name: use another repository action
on: push
jobs:
    test-action:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: check directory
              run: |
                ls
            - name: checkout another repository
              uses: actions/checkout@v4
              with:
                repository: lonely-takumi/reusable-workflow-repository
                ref: main
                path: /home/runner/work/
            - name: check directory
              run: |
                ls
            - name: move work directory
              run: |
                cd /home/runner/work/
                ls
